#!/bin/bash

bin/gn gen out/android-arm-debug --args='ndk="'${ANDROID_NDK_ROOT}'" target_cpu="arm"'

echo ''
echo 'To compile, use command:'
echo "ninja -C out/android-arm-debug"

echo ''
echo "To Create viewer App:"
echo "b/android-build-app-debug viewer"


