#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo ""
    echo "Usage: android-build-app <appname>"
    echo ""
    exit
fi

echo ""
echo "Copy resources to app assets directory"
cp -a resources platform_tools/android/apps/$1/src/main/assets/

echo ""
echo "Copy Arm64 library"
mkdir -p platform_tools/android/apps/$1/src/main/libs/arm64-v8a
cp out/android-arm64-release/lib$1.so platform_tools/android/apps/$1/src/main/libs/arm64-v8a

echo "Copy Arm library"
mkdir -p platform_tools/android/apps/$1/src/main/libs/armeabi-v7a
cp out/android-arm-release/lib$1.so platform_tools/android/apps/$1/src/main/libs/armeabi-v7a

echo "Copy x64 library"
mkdir -p platform_tools/android/apps/$1/src/main/libs/x86_64
cp out/android-x64-release/lib$1.so platform_tools/android/apps/$1/src/main/libs/x86_64

echo "Copy x86 library"
mkdir -p platform_tools/android/apps/$1/src/main/libs/x86
cp out/android-x86-release/lib$1.so platform_tools/android/apps/$1/src/main/libs/x86

echo ""
echo "Build Android App"
platform_tools/android/bin/android_build_app -C out/android-arm64-release $1
