#!/bin/bash

bin/gn gen out/android-x86-debug --args='ndk="'${ANDROID_NDK_ROOT}'" target_cpu="x86"'

echo ''
echo 'To compile, use command:'
echo "ninja -C out/android-x86-debug"

echo ''
echo "To Create viewer App:"
echo "b/android-build-app-debug viewer"

echo ''
echo 'To deploy viewer, use command:'
echo "adb install out/android-arm64-debug/viewer.apk"
