#!/bin/bash

bin/gn gen out/android-arm64-debug --args='ndk="'${ANDROID_NDK_ROOT}'" target_cpu="arm64"'

echo ''
echo 'To compile, use command:'
echo "ninja -C out/android-arm64-debug"

echo ''
echo "To Create Arm64 viewer App:"
echo "b/android-build-arm64-app-debug viewer"

echo ''
echo "To Create Universal viewer App:"
echo "b/android-build-universal-app-debug viewer"
echo ''


