#!/bin/bash

bin/gn gen out/macos-x64-static --args="is_official_build=true \
skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false \
skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_system_icu=false \
skia_use_system_harfbuzz=false"

echo ''
echo 'To compile, use command:'
echo 'ninja -C out/macos-x64-static'
echo ''
