#!/bin/bash

bin/gn gen out/macos-x64-debug

echo ''
echo 'To compile, use command:'
echo 'ninja -C out/macos-x64-debug'

echo ''
echo 'To run HelloWorld, use command:'
echo 'out/macos-x64-debug/HelloWorld'

echo ''
echo 'To run viewer, use command:'
echo 'out/macos-x64-debug/viewer'
echo ''
