#!/bin/bash

bin/gn gen out/macos-x64-release --args='is_debug=false'

echo ''
echo 'To compile, use command:'
echo 'ninja -C out/macos-x64-release'

echo ''
echo 'To run HelloWorld, use command:'
echo 'out/macos-x64-release/HelloWorld'

echo ''
echo 'To run viewer, use command:'
echo 'out/macos-x64-release/viewer'
echo ''